source 'https://github.com/jiaojiaozhe/FFComponent_Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FFFlowerDemoComponent_UI_Example' do
  pod 'FFFlowerDemoComponent_UI', :path => '../'

  target 'FFFlowerDemoComponent_UI_Tests' do
    inherit! :search_paths

    
  end
end
